FROM golang:1.23-alpine

WORKDIR /app

RUN apk add --no-cache gcc musl-dev git curl bash

RUN curl -o /usr/local/bin/wait-for-it https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh && chmod +x /usr/local/bin/wait-for-it

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["sh", "-c", "/usr/local/bin/wait-for-it rabbitmq:5672 -- go run main.go"]