FROM golang:1.23-alpine

WORKDIR /app

RUN apk add --no-cache gcc musl-dev git

RUN git clone https://github.com/air-verse/air.git \
    && cd air \
    && go build -o /go/bin/air \
    && cd .. \
    && rm -rf air

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]